//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountName
    {
        public int AccId { get; set; }
        public string AccountName1 { get; set; }
        public int Acc_CashType { get; set; }
        public int Acc_Type { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> WareId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public decimal Balance { get; set; }
        public Nullable<decimal> TotalCreditLimit { get; set; }
        public Nullable<decimal> TransactionHigestAmount { get; set; }
        public Nullable<int> NoOfTranPerMonth { get; set; }
        public string Description { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
