//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acquisition
    {
        public int AcquisitionId { get; set; }
        public int AcquisitionOrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Brand { get; set; }
        public string Model { get; set; }
        public int Quantity { get; set; }
        public bool IsSubQuantity { get; set; }
        public int UnitId { get; set; }
        public bool IsAsap { get; set; }
        public Nullable<int> AspTime { get; set; }
        public Nullable<System.DateTime> AspDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string RequiredTime { get; set; }
        public string Description { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<int> AssignedQuantity { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<long> AssignedBy { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReturnedQuantity { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<long> ReturnedBy { get; set; }
    }
}
