//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcquisitionImage
    {
        public int ImageId { get; set; }
        public int AcquisitionId { get; set; }
        public string ImageName { get; set; }
        public string ImageOriginalName { get; set; }
    }
}
