//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_BCR
    {
        public int Id { get; set; }
        public long UserId { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public bool IsIN { get; set; }
        public bool IsSendDate { get; set; }
    }
}
