//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusiReceivedItemAssignList
    {
        public int BusItemRcvdId { get; set; }
        public int BusinessId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public int AcqId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> WareId { get; set; }
        public Nullable<int> LineId { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public long AssignedBy { get; set; }
        public int BusProId { get; set; }
    }
}
