//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatHistory
    {
        public long ConversationId { get; set; }
        public long SenderId { get; set; }
        public long ReceiverId { get; set; }
        public string Chat { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<bool> Seen { get; set; }
        public Nullable<System.DateTime> SeenTime { get; set; }
    }
}
