//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientList
    {
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string ClientCode { get; set; }
        public bool IsBuyer { get; set; }
        public bool IsSupplier { get; set; }
        public bool IsOutSourcer { get; set; }
        public bool IsLogistic { get; set; }
        public string Address { get; set; }
        public string AddressLine1 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string Website { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    }
}
