//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Raw_Cotton_Report_List
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string ReportName { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
