//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchedPartsReturnList
    {
        public long Id { get; set; }
        public int DispatchedId { get; set; }
        public int InventoryId { get; set; }
        public int LocationId { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> ReturnReasonId { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<long> ReturnBy { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<double> AcceptQuan { get; set; }
        public Nullable<long> AcceptBy { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public long Dis_Item_Id { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string ReturnTransactionName { get; set; }
    }
}
