//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPerFormanceReview_LikeUnLike
    {
        public int ReviewLikeId { get; set; }
        public int UserReviewId { get; set; }
        public long UserId { get; set; }
        public bool LikeStatus { get; set; }
        public System.DateTime LikeUnlikeDate { get; set; }
    }
}
