//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finished_Product_List
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public int TitleId { get; set; }
        public string Count_Name { get; set; }
        public Nullable<double> M_C_Qty { get; set; }
        public string Lot { get; set; }
        public System.DateTime Lot_StartedDate { get; set; }
        public string Bag { get; set; }
        public string KG { get; set; }
        public int UnitId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> Site_UnitId { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public long InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    }
}
