//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayList
    {
        public int Id { get; set; }
        public int HolidayPackId { get; set; }
        public string HolidayName { get; set; }
        public bool IsMultipleDay { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> MonthCount { get; set; }
        public int TotalDay { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Year { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
    }
}
