//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_History
    {
        public long ImportId { get; set; }
        public string VoucherName { get; set; }
        public string L_C { get; set; }
        public int InventoryId { get; set; }
        public double Quantity { get; set; }
        public string UnitName { get; set; }
        public long InsertedBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<long> ParentId { get; set; }
    }
}
