//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Pro_Waste_List
    {
        public long Id { get; set; }
        public long InventoryId { get; set; }
        public int LocationId { get; set; }
        public int Type { get; set; }
        public double Quantity { get; set; }
        public int UnitId { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public long InsertedBy { get; set; }
    }
}
