//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Monthly_Stock
    {
        public long Id { get; set; }
        public int InventoryId { get; set; }
        public long LocationId { get; set; }
        public double Quantity { get; set; }
        public int MonthId { get; set; }
        public string MonthName { get; set; }
        public int Year { get; set; }
        public System.DateTime DataInsertedDate { get; set; }
    }
}
