//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Minimum_Finish_List
    {
        public long Id { get; set; }
        public int InventoryId { get; set; }
        public int LocationId { get; set; }
        public double AvailableQuan { get; set; }
        public double MinimunQuan { get; set; }
        public System.DateTime FinishedDate { get; set; }
    }
}
