//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Application_List
    {
        public long LeaveId { get; set; }
        public long ApplicationUserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int ApproveStatus { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> PreStartDate { get; set; }
        public Nullable<System.DateTime> PreEndDate { get; set; }
        public string Reject_Reason { get; set; }
    }
}
