//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinePartsNotInstalledList
    {
        public int Id { get; set; }
        public int MachineId { get; set; }
        public int InvenLocId { get; set; }
        public int PartsId { get; set; }
        public double NotInstalledQuan { get; set; }
        public int UnitId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public long RefColId { get; set; }
        public Nullable<int> VoucherId { get; set; }
    }
}
