//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportedComment
    {
        public int Id { get; set; }
        public long CommentId { get; set; }
        public int ReportId { get; set; }
        public long ReportedBy { get; set; }
        public System.DateTime ReportedDate { get; set; }
    }
}
