//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Acc_Pay_MonthList
    {
        public int Id { get; set; }
        public int Salary_Pck_Acc_Id { get; set; }
        public int MonthId { get; set; }
        public string MonthName { get; set; }
    }
}
