//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteList
    {
        public int Id { get; set; }
        public string SiteName { get; set; }
        public string SiteAcronym { get; set; }
        public string Address { get; set; }
        public string AddressLine1 { get; set; }
        public string Country { get; set; }
        public string Statename { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string PostalCode { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public int Status { get; set; }
        public bool IsComposite { get; set; }
        public Nullable<int> UnitNumber { get; set; }
        public bool IsResidential { get; set; }
    }
}
