//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemList
    {
        public int StockItemId { get; set; }
        public Nullable<int> Bus_Ord_Id { get; set; }
        public Nullable<int> Busi_Spec_Id { get; set; }
        public System.DateTime StoreDate { get; set; }
        public long StoreBy { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public Nullable<long> DispatchedBy { get; set; }
    }
}
