//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItemList
    {
        public int ItemId { get; set; }
        public int InventoryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public Nullable<int> ExpiredDateCount { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    }
}
