//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpInventoryOrderList
    {
        public int Id { get; set; }
        public bool WareItem { get; set; }
        public bool StoreItem { get; set; }
        public int InventoryId { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
        public long OrderedBy { get; set; }
        public System.DateTime OrderedDate { get; set; }
    }
}
