//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsEditCount
    {
        public long Id { get; set; }
        public long RefTableColumnId { get; set; }
        public long TransactionId { get; set; }
        public long EditedBy { get; set; }
        public System.DateTime EditedDate { get; set; }
        public int ReasonId { get; set; }
        public Nullable<decimal> PreAmount { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public int TransType { get; set; }
    }
}
