//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Rating_List
    {
        public int UserRatingId { get; set; }
        public long UserId { get; set; }
        public long RatedBy { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime RatingDate { get; set; }
    }
}
