//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Machine_Parts
    {
        public int Id { get; set; }
        public int MachineId { get; set; }
        public string MachineAcronym { get; set; }
        public int PartsId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string ExpiredDate { get; set; }
        public System.DateTime ReplaceDate { get; set; }
        public string ReplaceDateName { get; set; }
        public Nullable<int> Left_Day { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<decimal> NotInstalledQuan { get; set; }
        public bool IsInstalled { get; set; }
        public Nullable<int> InvenLocId { get; set; }
        public Nullable<long> PartsReceivedBy { get; set; }
        public Nullable<System.DateTime> PartsReceivedDate { get; set; }
        public int MachineTypeId { get; set; }
    }
}
