//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProList_WithLC
    {
        public int InventoryId { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> ImportId { get; set; }
        public string LC { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string WareName { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> LineId { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> LastOrderId { get; set; }
        public double MinimumQuantity { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductType { get; set; }
        public string Model { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string BrandName { get; set; }
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public bool CanbeBreakable { get; set; }
        public Nullable<int> SubQuantity { get; set; }
        public Nullable<int> SubUnitId { get; set; }
        public string SubUnitName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool CanbeOrdered { get; set; }
        public bool CanbeSold { get; set; }
        public bool CanbeRepaired { get; set; }
        public bool CanbePerishable { get; set; }
        public bool CanbeTopup { get; set; }
        public bool CanbeReplaceable { get; set; }
        public bool HasReplacementWarranty { get; set; }
        public bool HasServiceWarranty { get; set; }
        public Nullable<int> WarrantyDays { get; set; }
        public Nullable<bool> IsWarrantyStartNow { get; set; }
        public Nullable<int> WarrantyDay { get; set; }
        public Nullable<int> WarrantyMonth { get; set; }
        public Nullable<int> WarrantyYear { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Description { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedDateName { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> IsMultiLocation { get; set; }
    }
}
