//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_All_Salary_Pay_His
    {
        public long Id { get; set; }
        public int EmpSalaryPayId { get; set; }
        public int UserId { get; set; }
        public int UserType { get; set; }
        public int PayType { get; set; }
        public Nullable<int> InernalAccId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankAccId { get; set; }
        public string BankAccSlipNo { get; set; }
        public long InsertBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string InsertedDateFormate { get; set; }
        public Nullable<int> PresentDay { get; set; }
        public Nullable<int> AbsentDay { get; set; }
        public Nullable<decimal> TtlAmntPresentDays { get; set; }
        public string EmpId { get; set; }
        public string UserName { get; set; }
        public string Picture { get; set; }
        public string InsertUser { get; set; }
        public string InsertUserPic { get; set; }
        public int SiteId { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string UserTypeName { get; set; }
        public int Gender { get; set; }
        public bool IsRevert { get; set; }
    }
}
