//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_All_WarehouseLists
    {
        public int Id { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseAcroynm { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string CreatedDateName { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
        public string UpdatedDateFormate { get; set; }
        public string UpdateUsername { get; set; }
        public string UpdateUserPic { get; set; }
        public string AssignUserName { get; set; }
        public string AllAssignUserId { get; set; }
    }
}
