//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Inven_Dis_Voucher_List
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string VoucherName { get; set; }
        public System.DateTime DispatchedDate { get; set; }
        public long DispatchedBy { get; set; }
        public string DispatchedDateName { get; set; }
        public string DispatchedUserName { get; set; }
        public string DispatchedUserPic { get; set; }
        public bool IsStore { get; set; }
        public int Type { get; set; }
        public int AssignType { get; set; }
    }
}
