//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Audit_Information
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public string OperationName { get; set; }
        public string ModuleName { get; set; }
        public string PageName { get; set; }
        public string TableName { get; set; }
        public int ColumnId { get; set; }
        public long UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string OperationTime { get; set; }
        public int OperationStatus { get; set; }
        public string OpStatusValue { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
    }
}
