//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_All_Loan_History
    {
        public int LoanId { get; set; }
        public long UserId { get; set; }
        public int UserType { get; set; }
        public int PayType { get; set; }
        public Nullable<int> InernalAccId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankAccId { get; set; }
        public string BankAccSlipNo { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public int PaidStatus { get; set; }
        public long LoanPaidBy { get; set; }
        public System.DateTime LoanPaidDate { get; set; }
        public string LoanPaidDateFormate { get; set; }
        public Nullable<long> LoanReceivedBy { get; set; }
        public Nullable<System.DateTime> LoanReceivedDate { get; set; }
        public string LoanReceivedDateFormate { get; set; }
        public bool DeductionFromSalary { get; set; }
        public Nullable<System.DateTime> LoanAmntReturnDeadLine { get; set; }
        public Nullable<decimal> DeductAmountPerMonth { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string SiteName { get; set; }
        public string UserName { get; set; }
        public string Picture { get; set; }
        public string DesignationName { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string LoanPaidUser { get; set; }
        public string LoanPaidUserPic { get; set; }
        public string LoanReceivedPaidUser { get; set; }
        public string LoanReceivedPaidUserPic { get; set; }
    }
}
