//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Branch_info
    {
        public int BranchId { get; set; }
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public int Status { get; set; }
        public string AddressLine1 { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public string State { get; set; }
        public Nullable<int> DivisonId { get; set; }
        public string DivisionName { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
        public string Updated_UserName { get; set; }
        public string Updated_UserPic { get; set; }
    }
}
