//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_All_InventoryList
    {
        public int InventoryId { get; set; }
        public string ProductName { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductType { get; set; }
        public string Model { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string BrandName { get; set; }
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public bool CanbeBreakable { get; set; }
        public Nullable<int> SubQuantity { get; set; }
        public Nullable<int> SubUnitId { get; set; }
        public string SubUnitName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool CanbeOrdered { get; set; }
        public bool CanbeSold { get; set; }
        public bool CanbeRepaired { get; set; }
        public bool CanbePerishable { get; set; }
        public bool CanbeTopup { get; set; }
        public bool CanbeReplaceable { get; set; }
        public bool HasReplacementWarranty { get; set; }
        public bool HasServiceWarranty { get; set; }
        public Nullable<int> WarrantyDays { get; set; }
        public Nullable<bool> IsWarrantyStartNow { get; set; }
        public Nullable<int> WarrantyDay { get; set; }
        public Nullable<int> WarrantyMonth { get; set; }
        public Nullable<int> WarrantyYear { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Description { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedDateName { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> ReservedQuantity { get; set; }
        public Nullable<double> Available_Quantity { get; set; }
        public int InMultipleLocation { get; set; }
        public Nullable<int> LocationId { get; set; }
    }
}
