//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sup_Pro_Lists
    {
        public int Id { get; set; }
        public int BusinessOrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> AcquisitionOrderId { get; set; }
        public string Proname { get; set; }
        public int Quantity { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> PerPiece { get; set; }
        public Nullable<decimal> TotalPriece { get; set; }
        public int ReceivedStatus { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
        public Nullable<int> AssignedQuantity { get; set; }
    }
}
