//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_All_Approved_AcquisitionList
    {
        public int AcquisitionId { get; set; }
        public int AcquisitionOrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProductType { get; set; }
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Brand { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public Nullable<int> Country { get; set; }
        public string CountryName { get; set; }
        public bool IsAsap { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string RequiredDateName { get; set; }
        public string RequiredTime { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedDateName { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int OrderStatus { get; set; }
        public bool IsSubQuantity { get; set; }
    }
}
