//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Dispacth_Item_Details
    {
        public long Id { get; set; }
        public int DispatchedId { get; set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
        public int InventoryId { get; set; }
        public int LocationId { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> ImportId { get; set; }
        public string LC { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> ReturnQuantity { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> Site_Unit_Id { get; set; }
        public string Site_Unit_Name { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string DeptName { get; set; }
        public string DeptName_Unit { get; set; }
        public Nullable<int> LineId { get; set; }
        public string LineName { get; set; }
        public bool IsAlreadyUsed { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public Nullable<long> DispatchedBy { get; set; }
        public string DispatchedDateName { get; set; }
        public string DispatchedUserName { get; set; }
        public string DispatchedUserPic { get; set; }
        public string VoucherName { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<int> ReturnReasonId { get; set; }
        public Nullable<double> UsedQuan { get; set; }
        public string ReturnDateName { get; set; }
        public string ReturnUserName { get; set; }
        public string ReturnUserPic { get; set; }
        public Nullable<int> WareId { get; set; }
        public string WardName { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> AssignType { get; set; }
    }
}
