//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Indent_Transaction
    {
        public long Id { get; set; }
        public string TransactionName { get; set; }
        public long VoucherId { get; set; }
        public string Name { get; set; }
        public long IndentId { get; set; }
        public string ProName { get; set; }
        public double Quantity { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string InsertedDateName { get; set; }
        public long InsertedBy { get; set; }
        public string InsertedUserName { get; set; }
        public string InsertedUserPic { get; set; }
        public Nullable<int> IndentType { get; set; }
        public Nullable<double> Required_Qty { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> ProUnitPrice { get; set; }
        public string Comments { get; set; }
    }
}
