//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Leave_Application
    {
        public long LeaveId { get; set; }
        public long ApplicationUserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public string StartDateFormate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string EndDateFormate { get; set; }
        public int ApproveStatus { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedDateFormate { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string ApprovedUserName { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string AppliedDateFormate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> PreStartDate { get; set; }
        public Nullable<System.DateTime> PreEndDate { get; set; }
        public string Reject_Reason { get; set; }
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public string SiteName { get; set; }
        public int SiteId { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string Picture { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsInLeave { get; set; }
    }
}
