//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Inventory_Finish_Item_List
    {
        public string LC { get; set; }
        public long Id { get; set; }
        public int InventoryId { get; set; }
        public int LocationId { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> Total_Quan { get; set; }
        public double AvailableQuan { get; set; }
        public double MinimunQuan { get; set; }
        public System.DateTime FinishedDate { get; set; }
        public string FinishedDateFormate { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedDateFormate { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<long> ImportId { get; set; }
    }
}
