//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Chat_History
    {
        public long ConversationId { get; set; }
        public long SenderId { get; set; }
        public string SenderName { get; set; }
        public long ReceiverId { get; set; }
        public string ReveiverName { get; set; }
        public string Chat { get; set; }
        public System.DateTime SendDate { get; set; }
        public string SendDateFormate { get; set; }
        public string SendTime { get; set; }
        public Nullable<bool> Seen { get; set; }
        public string SeenTime { get; set; }
        public string SeenDateFormate { get; set; }
    }
}
