//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Daily_Attendance
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime AttDate { get; set; }
        public string AttTime { get; set; }
        public System.DateTime AttDatetime { get; set; }
        public long InsertedBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public int AttType { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public string EmpId { get; set; }
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public string DeptName { get; set; }
        public int DeptId { get; set; }
        public string DesignationName { get; set; }
        public int DesignationId { get; set; }
        public string UserName { get; set; }
        public string Picture { get; set; }
        public string UserTypeName { get; set; }
        public int UserType { get; set; }
        public int Gender { get; set; }
        public string AttTypeName { get; set; }
        public string LeaveName { get; set; }
        public string InsertedUserName { get; set; }
        public string InsertedUserPic { get; set; }
    }
}
