//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Routedhistory
    {
        public long Id { get; set; }
        public int InventoryId { get; set; }
        public int DispatchedId { get; set; }
        public int LocationId { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> UsedQuan { get; set; }
        public Nullable<double> ReturnQuantity { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> WareId { get; set; }
        public string StoreAcroynm { get; set; }
        public string StoreName { get; set; }
        public string VoucherName { get; set; }
        public System.DateTime DispatchedDate { get; set; }
        public long DispatchedBy { get; set; }
        public string Picture { get; set; }
        public string UserName { get; set; }
        public long UserId { get; set; }
        public string ProductName { get; set; }
    }
}
