//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Invoice_Service
    {
        public int Id { get; set; }
        public int ServiceType { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedDateName { get; set; }
        public string CreatedUserName { get; set; }
        public string CreatedUserPic { get; set; }
        public int VoucherId { get; set; }
        public string VoucherTitle { get; set; }
        public string Number { get; set; }
        public int VoucherTypeId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string VoucherTypeName { get; set; }
        public int Status { get; set; }
        public Nullable<int> InternalAccId { get; set; }
        public Nullable<int> BankAccId { get; set; }
        public string InternalAccName { get; set; }
        public string BankAccName { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> WareId { get; set; }
        public string SiteName { get; set; }
        public string UnitName { get; set; }
        public string DeptName { get; set; }
        public string LineName { get; set; }
        public string StoreName { get; set; }
        public string WareName { get; set; }
    }
}
