//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Line_Machine_Info
    {
        public int Id { get; set; }
        public int MachineId { get; set; }
        public string MachineAcronym { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> AssignStatus { get; set; }
        public Nullable<int> MachineTypeId { get; set; }
        public int LineId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string LineName { get; set; }
        public string LineAcronym { get; set; }
        public Nullable<int> NumberOfMachine { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public long AssignedBy { get; set; }
        public string AssignedUserName { get; set; }
        public string AssignedUserPic { get; set; }
        public string AssignedDateName { get; set; }
    }
}
