//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Busi_Details_ForClient
    {
        public int BusinessOrderId { get; set; }
        public int OrderType { get; set; }
        public string OrderName { get; set; }
        public int OrderStatus { get; set; }
        public string OrderAprvStatus { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalProCost { get; set; }
        public Nullable<decimal> TotalOthersCost { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UserName { get; set; }
        public string PictureName { get; set; }
        public string HasSpec { get; set; }
    }
}
