//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllAttendance
    {
        public long UserId { get; set; }
        public string EmpId { get; set; }
        public string CardNumber { get; set; }
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Picture { get; set; }
        public int UserType { get; set; }
        public string UserTypeName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Gender { get; set; }
        public int Id { get; set; }
        public string Card_UID { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string CardInsertStatus { get; set; }
        public string EntryDate { get; set; }
        public long InsertedBy { get; set; }
        public System.DateTime EntryDateTime { get; set; }
    }
}
