//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingScheduleList
    {
        public int WorkingScheduleId { get; set; }
        public string SchedulName { get; set; }
        public Nullable<int> NoOfPaidLeave { get; set; }
        public string StartTime { get; set; }
        public string Start_Allowance { get; set; }
        public string EndTime { get; set; }
        public string End_Allowance { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<decimal> BreakTime { get; set; }
        public Nullable<int> BreakTimeType { get; set; }
        public bool SameWorkHour { get; set; }
    }
}
